name: Main - Testing

on:
  push:
    branches:
      - 'main'

jobs:
  artifact:
    name: Test Main Branch
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
      - name: NPM Install Dependencies
        run: npm install
      - name: Test Node Environment
        run: npm test
